### ISSUE TITLE
make the report less verbose

### ISSUE THREAD

**Issue by fredericoschardong** [str0zzapreti/pytest-retry#40]
Thank you for this extension to pytest, it is great.

Our only issue is that we cannot control the verbosity level of the report. We often have thousands of lines of the same stacktrace, which takes a lot of space in our CI/CD. How can we control this? We are using `pytest -vv` which used to produce a few hundred lines at most, and by adding `pytest-retry` we jumped to the thousands.

Thank you.

**Comment by str0zzapreti** [comment]
I'll take a look at this soon, thanks for the report!

**Comment by str0zzapreti** [comment]
Just created a new PR for this @fredericoschardong here: https://github.com/str0zzapreti/pytest-retry/pull/41
This is actually an easy fix, I simply configured pytest-retry to use the existing verbosity counter rather than simply switching off the trace limit when verbose mode is enabled. This should result in a trace depth of 2 with your `pytest -vv` command specifically which will be much more manageable than the trace depth of 40-50 that you've been seeing up to this point. If this still isn't enough granularity for you, it would be simple for me to add an additional config option to control trace depth as well, just let me know. I'm still planning to add a test for the change so let me know when you've had a chance to look at the PR and I'll go ahead with the solution we decide on.

Thanks for the report!

**Comment by str0zzapreti** [comment]
Fixed in [1.6.3](https://github.com/str0zzapreti/pytest-retry/tree/1.6.3)

Should be available on Pypi shortly
